.TH "BC.h" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BC.h \- A Documented file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'iostream'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBgamma\fP   1\&.4"
.br
.ti -1c
.RI "#define \fBgasconstant\fP   287\&.14"
.br
.ti -1c
.RI "#define \fBheatcapacityconstantvolume\fP   717\&.5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnormal\fP (vector< double > &v)"
.br
.ti -1c
.RI "void \fBBC\fP (vector< vector< vector< vector< double > > > > &variablesvector, vector< vector< vector< vector< double > > > > &y_face_area, vector< vector< vector< vector< double > > > > &z_face_area, int Nx, int Ny, int Nz)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Documented file\&. 

Details\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Degree Project from the source code\&.
