.TH "bug" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBClass \fBdiffusionfluxinterface\fP \fP" 1c
Not all memory is freed when deleting an object of this class\&.  
.IP "\fBClass \fBnetfluxinterface\fP \fP" 1c
Not all memory is freed when deleting an object of this class\&. 
.PP

