.TH "diffusionfluxinterface" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diffusionfluxinterface \- Pretty nice class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <diffusionfluxinterface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdiffusionfluxinterface\fP (vector< double > &vectorleftminus, vector< double > &vectorleft, vector< double > &vectorright, vector< double > &vectorrightplus, vector< double > &areavectorleft, vector< double > &areavectorright, vector< double > &areavectorrightplus, double volumeleftmins, double volumeleft, double volumeright, double volumerightplus, double deltat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBdiffusionfluxvector\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pretty nice class\&. 

This class is used to demonstrate a number of section commands\&. 
.PP
\fBAuthor:\fP
.RS 4
John Doe 
.PP
Jan Doe 
.RE
.PP
\fBVersion:\fP
.RS 4
4\&.1a 
.RE
.PP
\fBDate:\fP
.RS 4
1990-2011 
.RE
.PP
\fBPrecondition:\fP
.RS 4
First initialize the system\&. 
.RE
.PP
\fBBug\fP
.RS 4
Not all memory is freed when deleting an object of this class\&. 
.RE
.PP
\fBWarning:\fP
.RS 4
Improper use can crash your application 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "diffusionfluxinterface::diffusionfluxinterface (vector< double > & vectorleftminus, vector< double > & vectorleft, vector< double > & vectorright, vector< double > & vectorrightplus, vector< double > & areavectorleft, vector< double > & areavectorright, vector< double > & areavectorrightplus, double volumeleftmins, double volumeleft, double volumeright, double volumerightplus, double deltat)\fC [inline]\fP"
< Detailed description after the member
.PP
< enum value 1
.PP
A pure virtual member\&.
.PP
\fBSee also:\fP
.RS 4
testMe() 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIc1\fP the first argument\&. 
.br
\fIc2\fP the second argument\&.
.RE
.PP
A list of events:
.IP "\(bu" 2
mouse events
.IP "  1." 6
The distance between $(x_1,y_1)$ and $(x_2,y_2)$ is $\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}$\&.
.IP "  2." 6
mouse move event
.IP "  3." 6
mouse click event
.br
 More info about the click event\&.
.IP "  4." 6
mouse double click event
.PP

.IP "\(bu" 2
keyboard events
.IP "  1." 6
\fClink text\fP
.IP "  2." 6
key up event
.PP
.IP "  2." 6
\fClink text\fP
.PP

.PP
.PP
More text here\&.
.PP
Complex tableColumn 1 Column 2 Column 3 cell row=1+2,col=1cell row=1,col=2cell row=1,col=3 cell row=2+3,col=2 cell row=2,col=3 cell row=3,col=1 cell row=3+4,col=3 cell row=4,col=1+2 cell row=5,col=1 cell row=5,col=2+3 cell row=6+7,col=1+2 cell row=6,col=3 cell row=7,col=3 cell row=8,col=1 cell row=8,col=2
.br
 Inner cell row=1,col=1Inner cell row=1,col=2 Inner cell row=2,col=1Inner cell row=2,col=2 cell row=8,col=3 
.PD 0

.IP "\(bu" 2
Item 1 
.IP "\(bu" 2
Item 2 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Degree Project from the source code\&.
