.TH "eulerflux" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eulerflux \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeulerflux\fP (vector< double > &vector)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBxeulerflux\fP [5]"
.br
.ti -1c
.RI "double \fByeulerflux\fP [5]"
.br
.ti -1c
.RI "double \fBzeulerflux\fP [5]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Degree Project from the source code\&.
