.TH "interface" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinterface\fP (vector< double > &vectorleft, vector< double > &vectorright, vector< double > &areavectorinterface, double volumeleft, double volumeright, double deltat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBdensityinterface\fP"
.br
.ti -1c
.RI "double \fBxvelocityinterface\fP"
.br
.ti -1c
.RI "double \fByvelocityinterface\fP"
.br
.ti -1c
.RI "double \fBzvelocityinterface\fP"
.br
.ti -1c
.RI "double \fBenthalpyinterface\fP"
.br
.ti -1c
.RI "double \fBvectorjumpinterface\fP [5]"
.br
.ti -1c
.RI "double \fBeigenvalue\fP [5]"
.br
.ti -1c
.RI "double \fBeigenvectormatrix\fP [5][5]"
.br
.ti -1c
.RI "double \fBeigenvectormatrixinvers\fP [5][5]"
.br
.ti -1c
.RI "double \fBalphavectorinterface\fP [5]"
.br
.ti -1c
.RI "double \fBmuvectorinterface\fP [5]"
.br
.ti -1c
.RI "double \fBZvectorinterface\fP [5]"
.br
.ti -1c
.RI "double \fBpshivectorinterface\fP [5]"
.br
.ti -1c
.RI "double \fBgvectorinterface\fP [5]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Degree Project from the source code\&.
