.TH "netfluxinterface" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netfluxinterface \- Pretty nice class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <netfluxinterface\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnetfluxinterface\fP (vector< double > &vectorleftminus, vector< double > &vectorleft, vector< double > &vectorright, vector< double > &vectorrightplus, vector< double > &areavectorleft, vector< double > &areavectorright, vector< double > &areavectorrightplus, double volumeleftmins, double volumeleft, double volumeright, double volumerightplus, double deltat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBnetflux\fP [5]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pretty nice class\&. 

This class is used to demonstrate a number of section commands\&. 
.PP
\fBAuthor:\fP
.RS 4
John Doe 
.PP
Jan Doe 
.RE
.PP
\fBVersion:\fP
.RS 4
4\&.1a 
.RE
.PP
\fBDate:\fP
.RS 4
1990-2011 
.RE
.PP
\fBPrecondition:\fP
.RS 4
First initialize the system\&. 
.RE
.PP
\fBBug\fP
.RS 4
Not all memory is freed when deleting an object of this class\&. 
.RE
.PP
\fBWarning:\fP
.RS 4
Improper use can crash your application 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Public License\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "netfluxinterface::netfluxinterface (vector< double > & vectorleftminus, vector< double > & vectorleft, vector< double > & vectorright, vector< double > & vectorrightplus, vector< double > & areavectorleft, vector< double > & areavectorright, vector< double > & areavectorrightplus, double volumeleftmins, double volumeleft, double volumeright, double volumerightplus, double deltat)\fC [inline]\fP"
< Detailed description after the member
.PP
< [out] docs for input parameter v\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Degree Project from the source code\&.
