.TH "Test" 3 "Mon Feb 20 2017" "Dual Degree Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test \- This is a test class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This is a test class\&. 

Some details about the \fBTest\fP class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Dual Degree Project from the source code\&.
