var searchData=
[
  ['getarearatio',['getAreaRatio',['../initial__condition_8h.html#a3954c41c7a67bc08d0bb137807b49e6f',1,'initial_condition.h']]],
  ['getmach',['getMach',['../initial__condition_8h.html#aa49e9b4061bb2f4c566d4157723ca254',1,'initial_condition.h']]],
  ['getnormal',['getNormal',['../BC_8h.html#a957d570922df67a298ed1d9bad6fe098',1,'BC.h']]],
  ['grid',['grid',['../grid__ideal__nozzle_8h.html#a0195a06d59a6445d9ef8d27b775caeb0',1,'grid(vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;iFaceAreaVectorIn, vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;jFaceAreaVectorIn, vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;kFaceAreaVectorIn, vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &amp;CellVolumeIn, vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &amp;dsIn, int &amp;Ni, int &amp;Nj, int &amp;Nk, int GeometryOption):&#160;grid_ideal_nozzle.h'],['../grid__nozzle_8h.html#a6cdf5cf168063009e847db46d6624c1b',1,'grid(vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;iFaceAreaVectorIn, vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;jFaceAreaVectorIn, vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;kFaceAreaVectorIn, vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &amp;CellVolumeIn, vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &amp;dsIn, int &amp;Ni, int &amp;Nj, int &amp;Nk):&#160;grid_nozzle.h'],['../TVD_8cpp.html#a7d56149ed8fe8b17760b54f9bdffc052',1,'grid(vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;iFaceAreaVector, vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;jFaceAreaVector, vector&lt; vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &gt; &amp;kFaceAreaVector, vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &amp;CellVolume, vector&lt; vector&lt; vector&lt; double &gt; &gt; &gt; &amp;delta_s, int &amp;Ni, int &amp;Nj, int &amp;Nk, int GeometryOption):&#160;grid.h']]],
  ['grid_5fideal_5fnozzle_2eh',['grid_ideal_nozzle.h',['../grid__ideal__nozzle_8h.html',1,'']]],
  ['grid_5fnozzle_2eh',['grid_nozzle.h',['../grid__nozzle_8h.html',1,'']]]
];
